config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql' if Rails.env.development?
  post '/graphql', to: 'graphql#execute'
  root 'pages#home'
  devise_for :accounts
  mount Sidekiq::Web => '/sidekiq'
end

app/models/account.rb
# Account model for authentication with Devise
class Account < ApplicationRecord
  devise :database_authenticatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rating.rb
# Rating model for a given Whiskey and a given Account
class Rating < ApplicationRecord
  enum quality: %i[taste color smokiness]
  enum stars: %i[no_stars one two three four five]
  belongs_to :account
  belongs_to :whiskey
  validates :account, presence: true
  validates :whiskey, presence: true
  validates :quality, uniqueness: { scope: %i[account_id whiskey_id] }
end

app/models/whiskey.rb
# the whiskey model
class Whiskey < ApplicationRecord
  include PgSearch::Model
  has_one_attached :photo
  has_many :ratings, inverse_of: :whiskey, dependent: :destroy
  pg_search_scope :search_text, against: %i[title description]

  scope :minimum_5stars, -> { joins(:ratings).where(ratings: { stars: :five }) }
  scope :minimum_4stars, -> { joins(:ratings).where(ratings: { stars: %i[four five] }) }
  scope :minimum_3stars, -> { joins(:ratings).where(ratings: { stars: %i[three four five] }) }
  scope :minimum_2stars, -> { joins(:ratings).where(ratings: { stars: %i[two three four five] }) }
  scope :minimum_1star, -> { joins(:ratings).where(ratings: { stars: %i[one two three four five] }) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/graphql_controller.rb
# GraphQL Controller
class GraphqlController < ApplicationController
  # If accessing from outside this domain, nullify the session
  # This allows for outside API access while preventing CSRF attacks,
  # but you'll have to authenticate your user separately
  # protect_from_forgery with: :null_session

  def execute
    variables = ensure_hash(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      # Query context goes here, for example:
      # current_user: current_user,
    }
    result = RubyOnWhalesBSideSchema.execute(query,
                                             variables: variables,
                                             context: context,
                                             operation_name: operation_name)
    render json: result
  rescue StandardError => e
    raise e unless Rails.env.development?

    handle_error_in_development e
  end

  private

  # Handle form data, JSON body, or a blank value
  def ensure_hash(ambiguous_param)
    case ambiguous_param
    when String
      if ambiguous_param.present?
        ensure_hash(JSON.parse(ambiguous_param))
      else
        {}
      end
    when Hash, ActionController::Parameters
      ambiguous_param
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{ambiguous_param}"
    end
  end

  def handle_error_in_development(error)
    logger.error error.message
    logger.error error.backtrace.join("\n")

    render json: { error:
                     { message: error.message, backtrace: error.backtrace }, data: {} }, status: :internal_server_error
  end
end

app/controllers/pages_controller.rb
# the home page controller
class PagesController < ApplicationController
  def home; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Ruby on Whales B-Side</title>
    <meta name="version" content="<%= ::VERSION %>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Fira+Sans&display=swap' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class = "notice" ><%= notice %></p>
    <p class = "alert" ><%= alert %></p>
    <%= yield %>
    <p class="copyright">&copy; Aventine Solutions 2020</p>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Ruby on Whales B-Side</h1>
<% if current_account %>
  <%= link_to "Sign Out", destroy_account_session_path, method: :delete %>
  <h2>Hello <code><%= current_account.email %></code></h2>
  <div id="root" data-account-id="<%= current_account.id if current_account.present? %>"/>
  <%= javascript_pack_tag 'index' %>
<% else %>
  <%= link_to "Sign In", new_account_session_path %>
<% end %>